variables:
  DEPLOY_TAG: "lyanna_giarrizzo_fr"
  DEPLOY_TO: "friday.giarrizzo.fr"
  SLACK_PAYLOAD: "payload={\"channel\": \"#deploy\", \"username\": \"Site_Giarrizzo\", \"text\": \"Lyanna - Deploy started : ${CI_JOB_URL}.\", \"icon_emoji\": \":ghost:\"}"

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      command: ["--insecure-registry=registry.gitlab.com"]
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CONTAINER_IMAGE} .
  after_script:
    - docker push ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  image: "bgiarrizzo/ansible-ci"
  before_script:
    - curl -X POST --data-urlencode "${SLACK_PAYLOAD}" ${SLACK_API}
    - mkdir -p ~/.ssh/
    - echo "${secret_key_deploy}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - echo "${public_key_deploy}" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cd Deploy/ && ansible-playbook playbook.yml -i hosts.yml --limit="${DEPLOY_TO}" --tags="${DEPLOY_TAG}"
